version: "3.7"
services:
    node-server1:
        restart: unless-stopped
        build:
            context: ./app
        ports:
            - "5001:5001"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - nodejs-data:/usr/src/app 
            
    node-server2:
        restart: unless-stopped
        build:
            context: ./app2
        ports:
            - "5002:5002"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - nodejs2-data:/usr/src/app 
            
    node-server3:
        restart: unless-stopped
        build:
            context: ./app3
        ports:
            - "5003:5003"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - nodejs3-data:/usr/src/app 
            
    nginx:
        restart: unless-stopped
        build:
            context: ./nginx
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - type: bind
              source: ./etc/nginx/conf.d
              target: nginx-data:
            
volumes:
        nginx-data:
        nodejs-data:
        nodejs2-data:
        nodejs3-data:
