version: "3.7"
services:
    node-svr:
        restart: unless-stopped
        build:
            context: .
        ports:
            - "5001-5005:5001"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - nodejs1-data:/usr/src/app           
            
volumes:
        nodejs1-data:
                driver: local
                external: true

