version: "3.7"
services:
    node-server:
        restart: unless-stopped
        build:
            context: ./app
        ports:
            - "5000:5000"
        volumes:
            - nodejs-data:/usr/src/app 
    nginx:
        restart: unless-stopped
        build:
            context: ./nginx
        ports:
            - "80:80"
        volumes:
            - nginx-data:/etc/nginx/conf.d
volumes:
        nginx-data:
        nodejs-data:
